const mongoose = require('mongoose');

const formDataSchema = new mongoose.Schema({
  name: { type: String },
  dob: { type: String },
  age: { type: Number },
  mobileNumber: { type: String },
  whatsappNumber: { type: String },
  aadharNumber: { type: String },
  email: { type: String },
  address: { type: String },
  fathersName: { type: String },
  fathersOccupation: { type: String },
  fathersContactNumber: { type: String },
  homePhone: { type: String },
  mothersName: { type: String },
  siblingName: { type: String },
  propertyDealer: { type: String },
  durationOfStay: { type: String },
  dealersContactNumber: { type: String },
  policeStationHomeTown: { type: String },
  buildingNumber: { type: String },
  roomNumber: { type: String },
  rentPerDay: { type: String },
  rentPerMonth: { type: String },
  roomUnit: { type: String },
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  room: { type: mongoose.Schema.Types.ObjectId, ref: 'roomListing' },
  contactTable: [
    {
      type: { type: String },
      name: { type: String },
      contactNumber: { type: String },
      relation: { type: String },
      _id: false,
    },
  ],
  paymentInformation: { type: Object },
  inDate: { type: String, required: true },
  agreementStartDate: { type: String, required: true },
  agreementEndDate: { type: String, required: true },
  lockInDate: { type: String, required: true },
  createdAt: { type: Date, default: Date.now },
  rentForRemainingDays: { type: Number },
  daysRemainingInMonth: { type: Number },
  totalRent: { type: Number },
});

const FormData = mongoose.model('FormData', formDataSchema);
module.exports = FormData;